version: 2.1
orbs:
  node: circleci/node@1.1.6
  coverage-reporter: codacy/coverage-reporter@10.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test-coverage
            - coverage-reporter/send_report
workflows:
  build-and-test:
    jobs:
      - build-and-test
